### ISSUE TITLE
Not working eith 3.1.6

### ISSUE THREAD

**Issue by MESWEB** [o0johntam0o/phpBB-Extension-Codebox-Plus#10]
I'm install new version of this mod but messages can't be render.

**Comment by o0johntam0o** [comment]
Did you disable the option "Enable syntax highlighting"?

**Comment by MESWEB** [comment]
No. How to do this?

**Comment by o0johntam0o** [comment]
Take a look in the ACP, you'll see it

**Comment by MESWEB** [comment]
Sorry I can't find or there is no any "Enable syntax highlighting". Any way I have no time for Your games.

**Comment by o0johntam0o** [comment]
There's a tip for you: https://www.phpbb.com/extensions/installing/ (How to install/remove an extension), and also check if the version of phpBB that compatible with this version of Codebox Plus
Regards.

**Comment by MESWEB** [comment]
Are you kidding me? I have installed this shitest mod! In ACP - there IS NO OPTION CALLED: "Enable syntax highlighting".

**Comment by o0johntam0o** [comment]
http://i301.photobucket.com/albums/nn74/o0johntam0o/phpBB/Codebox%20Plus%20Extension/ACP_zpshtiw61oz.png

(Thanks for choosing this shitest extension)

**Comment by MESWEB** [comment]
No I didn't see this tab because there are not existing in extension tab. I didn't know about this tab after You show me on this image. Some reason this mod didn't install correctly.

**Comment by o0johntam0o** [comment]
How to install an extension: https://www.phpbb.com/extensions/installing/

**Comment by MESWEB** [comment]
I'm not stupid and I know how to install. But I don't know why this mod don't work with 3.1.6. After update to 3.1.8 works pretty well.
