### ISSUE TITLE
Exception: The file "services.yml" does not contain valid YAML.

### ISSUE THREAD

**Issue by Hideman85** [o0johntam0o/phpBB-Extension-Codebox-Plus#14]
I clone your git and upload your extension to <root>/ext/ and when i enable your extension :
Exception: The file "<root>/ext/o0johntam0o/codeboxplus/config/services.yml" does not contain valid YAML.

PhpBB version : PhpBB 3.2 ( git clone yesterday )

Online YAML Parser : http://yaml-online-parser.appspot.com/

ERROR:

while scanning for the next token
found character '@' that cannot start any token
  in "<unicode string>", line 5, column 15:
                - @controller.helper

Attached commit : https://tracker.phpbb.com/browse/PHPBB3-14247

**Comment by Galixte** [comment]
Hi @o0johntam0o,

coul you take a look, please ?

**Comment by o0johntam0o** [comment]
Thanks for the report, I'll take a look at this.
Regards.

**Comment by Hideman85** [comment]
After research I find the solution ...

It's due to new feature of PhpBB 3.2

1) It use YAML 1.2 instead of YAML 1.1
so string must be quoted change :
all - @controller.helper  to  - '@controller.helper'

2) It use Php 7.0 instead of 5.6 
so all preg_relace('regex/e', my_function_to_call($1, $2));
need replace to preg_replace_callback('regex', function($str){ my_function_to_call($1, $2) });
Exemple : http://stackoverflow.com/questions/19245205/replace-deprecated-preg-replace-e-with-preg-replace-callback

Maybe you need to change other things ...
And maybe you need create an other branch ;)

Thanks you for your ext and good luck for update it ;)

**Comment by o0johntam0o** [comment]
The issue's fixed, but Codebox Plus's still not available for phpBB 3.2.
Thanks for the feedbacks.
Regards.

**Comment by Galixte** [comment]
@Hideman85 to know if the extension supports phpBB 3.2.x, see this line in composer.json: https://github.com/o0johntam0o/phpBB-Extension-Codebox-Plus/blob/master/ext/o0johntam0o/codeboxplus/composer.json#L32

**Comment by o0johntam0o** [comment]
@Galixte Opps, that's my mistake, I'll correct it later
