### ISSUE TITLE
Fatal Error when clicking Details under the Options column for installed extensions.

### ISSUE THREAD

**Issue by Josephur** [o0johntam0o/phpBB-Extension-Codebox-Plus#3]
All of my other extensions details work, only happens with CodeBox Plus.

phpBB version is 3.1.2

Fatal error: Wrong parameters for Exception([string $exception [, long $code [, Exception $previous = NULL]]]) in /home/content/87/xxxxxxxx/html/forum/phpbb/file_downloader.php on line 72

**Comment by o0johntam0o** [comment]
Codebox Plus is not ready for phpBB 3.1.2 at the moment.
This issue will be fixed on the next version of Codebox Plus

==> FIXED
