### ISSUE TITLE
BBcode gets disabled after editing a post

### ISSUE THREAD

**Issue by murk-sy** [o0johntam0o/phpBB-Extension-Codebox-Plus#4]
phpBB 3.1.2
With following extensions and no mods
- Board Announcements   1.0.0
- Board Rules   1.0.1
- Codebox Plus  1.0.0
- Pages     1.0.0
- Prime Ban to Group    1.0.2
- Referrers     3.1.0
- Reputation System     1.0.0-dev
  Only Codebox Plus seems to affect it.

_Steps to reproduce:_
1) Create a reply/quote with BBcode - post appears normal
2) Enter post editing and submit without changing anything - bbcode is disabled but no tick is checked

_To fix a broken post:_
1) Enter post editing, tick disable BBcode and submit post
2) Enter post editing, untick disable BBcode and submit post

The issue appears at http://forum.stabyourself.net . If you would like a test account or any other information, let me know and I'll get right on it.

**Comment by o0johntam0o** [comment]
This is a known issue since phpBB 3.0
And I'm still waiting for a solution

**Comment by murk-sy** [comment]
I see, thanks. I'll let you know if I find anything myself.

**Comment by o0johntam0o** [comment]
Fixed in the commit d8a7518
